export interface Owner {
  name: string;
  location: string;
  whatsapp: string; // international format, no + or spaces, e.g. "919876543210"
}

export interface Product {
  id: string;
  title: string;
  category: string;
  brand: string;
  image: string;
  images: string[];
  sizes: string[];
  condition: 'Like New' | 'Excellent' | 'Good';
  price: number;
  rentalDays: number;
  securityDeposit: number;
  description: string;
  occasion: string;
  status?: 'Rented' | 'Available';
  owner: Owner;
}

export const PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Floral Printed Maxi Dress',
    category: 'Dresses',
    brand: 'Libas',
    image: '/images/floraldress.jpg',
    images: [
      '/images/floraldress.jpg',
      '/images/floraldress.jpg',
      '/images/floraldress.jpg',
    ],
    status: 'Rented',
    sizes: ['S', 'M', 'L'],
    condition: 'Excellent',
    price: 299,
    rentalDays: 3,
    securityDeposit: 500,
    description: 'A breezy floral maxi dress, perfect for daytime events and summer occasions. Lightweight fabric with a flattering flowy silhouette.',
    occasion: 'Casual',
    owner: { name: 'Priya Sharma', location: 'Faridabad, Haryana', whatsapp: '919876543210' },
  },
  {
    id: '2',
    title: 'Pink Ruffle Dress',
    category: 'Dresses',
    brand: 'Libas',
    image: '/images/pinkruffledress.jpg',
    images: [
      '/images/pinkruffledress.jpg',
      '/images/backruffledress.png',
      '/images/sideruffledress.png',
    ],
    sizes: ['M', 'L'],
    condition: 'Excellent',
    price: 349,
    rentalDays: 3,
    securityDeposit: 500,
    description: 'A romantic ruffled pink dress with a fitted bodice, great for parties and celebrations.',
    occasion: 'Party',
    owner: { name: 'Ananya Gupta', location: 'New Delhi', whatsapp: '919812345678' },
  },
  {
    id: '3',
    title: 'Black Party Gown',
    category: 'Party Wear',
    brand: 'Label Ritu Kumar',
    image: '/images/blackpartygown.jpg',
    images: [
      '/images/blackpartygown.jpg',
      '/images/blackpartygown.jpg',
      '/images/blackpartygown.jpg',
    ],
    sizes: ['M', 'L'],
    condition: 'Like New',
    price: 499,
    rentalDays: 3,
    securityDeposit: 1500,
    description: 'An elegant floor-length black gown with subtle embellishments � ideal for formal evenings and receptions.',
    occasion: 'Wedding',
    owner: { name: 'Ritika Malhotra', location: 'Gurugram, Haryana', whatsapp: '919898989898' },
  },
  {
    id: '4',
    title: 'Yellow Summer Dress',
    category: 'Dresses',
    brand: 'Biba',
    image: '/images/yellowsummerdress.jpg',
    images: [
      '/images/yellowsummerdress.jpg',
      '/images/yellowsummerdress.jpg',
      '/images/yellowsummerdress.jpg',
    ],
    sizes: ['S', 'M'],
    condition: 'Good',
    price: 279,
    rentalDays: 3,
    securityDeposit: 400,
    description: 'A cheerful yellow cotton dress, comfortable for day outings and casual get-togethers.',
    occasion: 'Brunch',
    owner: { name: 'Sneha Kapoor', location: 'Noida, Uttar Pradesh', whatsapp: '919911223344' },
  },
  {
    id: '5',
    title: 'Green Satin Dress',
    category: 'Party Wear',
    brand: 'Anouk',
    image: '/images/greensatingdress.jpg',
    images: [
      '/images/greensatingdress.jpg',
      '/images/greensatingdress.jpg',
      '/images/greensatingdress.jpg',
    ],
    sizes: ['S'],
    condition: 'Excellent',
    price: 348,
    rentalDays: 3,
    securityDeposit: 600,
    description: 'A sleek satin dress in emerald green with a subtle sheen, perfect for cocktail evenings.',
    occasion: 'Party',
    owner: { name: 'Meera Nair', location: 'Faridabad, Haryana', whatsapp: '919765432109' },
  },
  {
    id: '6',
    title: 'White Shirt Dress',
    category: 'Indo Western',
    brand: 'Manyavar',
    image: '/images/whiteshirtfress.jpg',
    images: [
      '/images/whiteshirtfress.jpg',
      '/images/whiteshirtfress.jpg',
      '/images/whiteshirtfress.jpg',
    ],
    sizes: ['M', 'L'],
    condition: 'Like New',
    price: 299,
    rentalDays: 3,
    securityDeposit: 400,
    description: 'A crisp, versatile white shirt dress that works for brunches, office events, or casual outings.',
    occasion: 'Office',
    owner: { name: 'Kavya Reddy', location: 'New Delhi', whatsapp: '919654321098' },
  },
  {
    id: '7',
    title: 'Embroidered Anarkali Gown',
    category: 'Lehenga',
    brand: 'Libas',
    image: '/images/anarkaligown.jpg',
    images: [
      '/images/anarkaligown.jpg',
      '/images/anarkaligown.jpg',
      '/images/anarkaligown.jpg',
    ],
    sizes: ['S', 'M', 'L'],
    condition: 'Excellent',
    price: 4499,
    rentalDays: 3,
    securityDeposit: 2000,
    description: 'A richly embroidered Anarkali gown with intricate threadwork, ideal for weddings and festive occasions.',
    occasion: 'Wedding',
    owner: { name: 'Divya Singh', location: 'Gurugram, Haryana', whatsapp: '919543210987' },
  },
  {
    id: '8',
    title: 'Black Indo Western Set',
    category: "Men's Wear",
    brand: 'Manyavar',
    image: '/images/blackindowestren.jpg',
    images: [
      '/images/blackindowestren.jpg',
      '/images/blackindowestren.jpg',
      '/images/blackindowestren.jpg',
    ],
    sizes: ['M', 'L', 'XL'],
    condition: 'Good',
    price: 699,
    rentalDays: 3,
    securityDeposit: 800,
    description: 'A sharp indo-western set combining a structured jacket with traditional detailing � great for sangeet and reception events.',
    occasion: 'Festive',
    owner: { name: 'Rohan Verma', location: 'Faridabad, Haryana', whatsapp: '919432109876' },
  },
  {
    id: '9',
    title: 'Designer Silk Saree',
    category: 'Saree',
    brand: 'Anouk',
    image: '/images/designersilksaree.jpg',
    images: [
      '/images/designersilksaree.jpg',
      '/images/designersilksaree.jpg',
      '/images/designersilksaree.jpg',
    ],
    sizes: ['S', 'M'],
    condition: 'Excellent',
    price: 399,
    rentalDays: 3,
    securityDeposit: 500,
    description: 'A pure silk saree with a woven border, elegant enough for weddings and pujas alike.',
    occasion: 'Festive',
    owner: { name: 'Lakshmi Iyer', location: 'New Delhi', whatsapp: '919321098765' },
  },
  {
    id: '10',
    title: 'Cotton Kurta Set',
    category: 'Kurta Set',
    brand: 'Biba',
    image: '/images/kurtaset.jpg',
    images: [
      '/images/kurtaset.jpg',
      '/images/kurtaset.jpg',
      '/images/kurtaset.jpg',
    ],
    sizes: ['M'],
    condition: 'Like New',
    price: 299,
    rentalDays: 3,
    securityDeposit: 300,
    description: 'A breathable cotton kurta set with simple block-print detailing, suited for festive daytime wear.',
    occasion: 'Casual',
    owner: { name: 'Arjun Mehta', location: 'Noida, Uttar Pradesh', whatsapp: '919210987654' },
  },
  {
    id: '11',
    title: 'Blue Party Wear Dress',
    category: 'Party Wear',
    brand: 'Label Ritu Kumar',
    image: '/images/bluepartywear.jpg',
    images: [
      '/images/bluepartywear.jpg',
      '/images/bluepartywear.jpg',
      '/images/bluepartywear.jpg',
    ],
    sizes: ['S'],
    condition: 'Excellent',
    price: 349,
    rentalDays: 3,
    securityDeposit: 500,
    description: 'A cobalt blue party dress with a structured fit, designed to stand out at evening celebrations.',
    occasion: 'Party',
    owner: { name: 'Ishita Bose', location: 'Gurugram, Haryana', whatsapp: '919109876543' },
  },
  {
    id: '12',
    title: 'Kids Festive Lehenga',
    category: 'Kids Wear',
    brand: 'Manyavar Kids',
    image: '/images/festivelehenga.jpg',
    images: [
      '/images/festivelehenga.jpg',
      '/images/festivelehenga.jpg',
      '/images/festivelehenga.jpg',
    ],
    sizes: ['XS', 'S'],
    condition: 'Excellent',
    price: 249,
    rentalDays: 3,
    securityDeposit: 300,
    description: 'A vibrant festive lehenga for kids, comfortable enough for a full day of celebrations and dancing.',
    occasion: 'Festive',
    owner: { name: 'Neha Joshi', location: 'Faridabad, Haryana', whatsapp: '919098765432' },
  },
];
